### ISSUE TITLE
[1.14.3] Crashes upon loading server

### ISSUE THREAD

**Issue by Zaxyul** [MrMarnic/AnimalNet#11]
```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.class_1863.method_8125(Lnet/minecraft/class_1860;)V
	at me.marnic.animalnet.mechanics.ServerHandler.handleServerStarting(ServerHandler.java:19)
	at net.minecraft.class_3176.handler$setup$zei000(class_3176.java:1183)
	at net.minecraft.class_3176.method_3823(class_3176.java:250)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
	at java.lang.Thread.run(Thread.java:748)
```

Here is the crash log I hope it helps!

Reproduction steps:
Launch the server and watch it burn!

Other info:
Server version 1.14.3 Fabric
Cleint: 1.14.3 Fabric
(Both with the API etc and it's all working otherwise it only breaks when AnimalNet is added and I launch the server) 
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_171, Oracle Corporation

(Last tiny note: It was working before on 1.14.2 for me but upon updating to 1.14.3 and updating all my mods this is one of the only ones that didn't work with the update so it's definitely something 1.14.3 related to my understanding)

**Comment by MrMarnic** [comment]
This error should be fixed in version v1.14.3 Fabric b1
