### ISSUE TITLE
fabric 1.14.3(server) got a recipe issue

### ISSUE THREAD

**Issue by SDUBZ** [MrMarnic/AnimalNet#13]
AN: AnimalNet-v1.14.3+Fabric+b1

[STDERR]: java.lang.NoSuchFieldException: recipeMap
[06:28:08] [Server thread/INFO]: [STDERR]:      at java.lang.Class.getDeclaredField(Unknown Source)
[06:28:08] [Server thread/INFO]: [STDERR]:      at me.marnic.animalnet.mechanics.ServerHandler.handleServerStarting(ServerHandler.java:30)
[06:28:08] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.handler$setup$zkd000(class_3176.java:1683)
[06:28:08] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3823(class_3176.java:250)
[06:28:08] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
[06:28:08] [Server thread/INFO]: [STDERR]:      at java.lang.Thread.run(Unknown Source)

**Comment by MrMarnic** [comment]
Which exact Minecraft version are you using?

**Comment by SDUBZ** [comment]
1.14.3

**Comment by MrMarnic** [comment]
I am sorry but foe me it is working on 1.14.3 Fabric

**Comment by MrMarnic** [comment]
Can you send me the full game log via pastebin please

**Comment by MrMarnic** [comment]
Thank you for all of this information. I have fixed the bug in "AnimalNet v1.14.3 Fabric b2"
