### ISSUE TITLE
Server stall: NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

### ISSUE THREAD

**Issue by RisingInIris2017** [MrMarnic/AnimalNet#29]
#### Mod version:

animalnet-v1.12.2+b3 

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, using [CatServer-0c9a30f-universal](https://github.com/Luohuayu/CatServer/releases/tag/20.02.03)

#### Installed mods:

![](https://user-images.githubusercontent.com/28519848/73504805-8da5be00-440b-11ea-82bc-fdec51738e2e.png)

#### How to reproduce:
1. Catch some mobs.
2. Trying to release them by keeping right-clicking with a Caught Mob item in the main hand.
3. Nothing is released, but server stalls.

Before the moment the server reported "stopped responding", there were always log reports like these below, keeping occurring:

[18:34:22] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_241]
        ...
Caused by: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at **me.marnic.animalnet**.common.item.ItemCaughtEntity.sendError(ItemCaughtEntity.java:164) ~[ItemCaughtEntity.class:?]
	at **me.marnic.animalnet**.common.item.ItemCaughtEntity.onItemUse(ItemCaughtEntity.java:134) ~[ItemCaughtEntity.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:890) ~[ForgeHooks.class:git-CatServer-1.12.2-0c9a30f]
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:213) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:598) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.util.Util.runTask(Util.java:529) ~[h.class:?]
	... 5 more

#### Link to full stall log:
latest.log 1: https://paste.ubuntu.com/p/4QzMb3QJZn/
latest.log 2: https://paste.ubuntu.com/p/D52q3g2XXT/

I do not know what did happen, but I think it is helpful to report this to you.
I hope to get your help sincerely. 
Look forward to your reply! 
Thanks in advance!

**Comment by MrMarnic** [comment]
I will try  to fix this.
