### ISSUE TITLE
crash on dedicated server

### ISSUE THREAD

**Issue by ImAK9** [MrMarnic/AnimalNet#6]
[20:24:07] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.class_1661.method_7395(Lnet/minecraft/class_1799;)I
    at me.marnic.animalnet.items.CaughtEntityItem.method_7884(CaughtEntityItem.java:191) ~[AnimalNet-1.6%20Fabric%2019w11b.jar:?]
    at net.minecraft.class_1799.method_7981(class_1799.java:189) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_3225.method_14262(class_3225.java:316) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_3244.method_12046(class_3244.java:945) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_2600.method_11072(class_2600.java:15) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_1255.method_18859(class_1255.java:135) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_1255.method_16075(class_1255.java:114) ~[intermediary-aof_server.jar:?]
    at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702) ~[intermediary-aof_server.jar:?]
    at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696) ~[intermediary-aof_server.jar:?]
    at net.minecraft.class_1255.method_5383(class_1255.java:99) ~[intermediary-aof_server.jar:?]
    at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:680) ~[intermediary-aof_server.jar:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [intermediary-aof_server.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by MrMarnic** [comment]
Can you tell me when this error happens?

**Comment by MrMarnic** [comment]
Are you using 19w11b or newer?

**Comment by ImAK9** [comment]
Fabric Loader: 0.4.5 build 140
Yarn: build 3

I'm using latest build

**Comment by MrMarnic** [comment]
Sorry,
I meant which Minecraft version are you using.

**Comment by ImAK9** [comment]
1.14

**Comment by MrMarnic** [comment]
The error is fixed in version "AnimalNet-1.7 Fabric 1.14"
