### ISSUE TITLE
[1.7 - MC-1.14 - OsX] - File error when releasing mobs from net

### ISSUE THREAD

**Issue by JaSpr** [MrMarnic/AnimalNet#8]
Displayed some text on the screen (wider than the screen) but I couldn't catch what it said before it disappeared.  Log below.   Note that this didn't cause a crash, and the animal was released from the net.  No negative effects that I know of, just the errors.

```
[18:36:09] [Server thread/INFO]: [STDOUT]: ddd
0.8099999570846563
[18:36:09] [Server thread/INFO]: [STDERR]: java.io.IOException: No such file or directory
[18:36:09] [Server thread/INFO]: [STDERR]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at java.io.File.createNewFile(File.java:1012)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at me.marnic.animalnet.items.CaughtEntityItem.createInstance(CaughtEntityItem.java:100)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at me.marnic.animalnet.mechanics.EntityHandler.addNetToInv(EntityHandler.java:93)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at me.marnic.animalnet.mechanics.EntityHandler.checkEntity(EntityHandler.java:63)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at me.marnic.animalnet.mechanics.EntityHandler.handleRightClick(EntityHandler.java:50)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at me.marnic.animalnet.items.AnimalNetItem.method_7847(AnimalNetItem.java:44)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7920(class_1799.java:325)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1657.method_7287(class_1657.java:1019)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_12062(class_3244.java:1187)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2824.method_12251(class_2824.java:69)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2824.method_11054(class_2824.java:13)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2600.method_11072(class_2600.java:15)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:135)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:114)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:123)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:681)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636)
[18:36:09] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
[18:36:29] [main/INFO]: [STDOUT]: Purged 164 chunks from cache
[18:36:40] [Server thread/INFO]: [STDOUT]: ddd
```

**Comment by MrMarnic** [comment]
Which Minecraft version and mod version are you using.

**Comment by MrMarnic** [comment]
Does that always happen if you try to catch an entity?
